secrets:
  postgres.password.txt:
    file: ./docker/secret.d/localhost/postgres.password.txt
services:
  flyway:
    command: migrate
    depends_on:
      - postgres
    image: boxfuse/flyway:5.2-alpine
    networks:
      postgres: null
    restart: on-failure
    volumes:
      - ./docker/secret.d/localhost/flyway.conf:/flyway/conf/flyway.conf:rw
      - ./migration:/flyway/sql:rw
  postgres:
    ports:
      - 127.0.0.1:5432:5432/tcp
    secrets:
      - source: postgres.password.txt
    volumes:
      - postgres:/var/lib/postgresql/data:rw
version: '3.6'
volumes:
  postgres: {}
