networks:
  etcd:
  symphony:
services:
  etcd_01:
    command: >-
      etcd
      -advertise-client-urls http://etcd_01:2379,http://etcd_01:4001
      -initial-advertise-peer-urls http://etcd_01:2380
      -initial-cluster etcd_01=http://etcd_01:2380,etcd_02=http://etcd_02:2380,etcd_03=http://etcd_03:2380
      -initial-cluster-state new
      -initial-cluster-token etcd-cluster-1
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -listen-peer-urls http://0.0.0.0:2380
      -name etcd_01
    image: quay.io/coreos/etcd:v3.4.9
    networks:
      - etcd
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
      - etcd_01:/etcd_01.etcd
  etcd_02:
    command: >-
      etcd
      -advertise-client-urls http://etcd_02:2379,http://etcd_02:4001
      -initial-advertise-peer-urls http://etcd_02:2380
      -initial-cluster etcd_01=http://etcd_01:2380,etcd_02=http://etcd_02:2380,etcd_03=http://etcd_03:2380
      -initial-cluster-state new
      -initial-cluster-token etcd-cluster-1
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -listen-peer-urls http://0.0.0.0:2380
      -name etcd_02
    image: quay.io/coreos/etcd:v3.4.9
    networks:
      - etcd
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
      - etcd_02:/etcd_02.etcd
  etcd_03:
    command: >-
      etcd
      -advertise-client-urls http://etcd_03:2379,http://etcd_03:4001
      -initial-advertise-peer-urls http://etcd_03:2380
      -initial-cluster etcd_01=http://etcd_01:2380,etcd_02=http://etcd_02:2380,etcd_03=http://etcd_03:2380
      -initial-cluster-state new
      -initial-cluster-token etcd-cluster-1
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -listen-peer-urls http://0.0.0.0:2380
      -name etcd_03
    image: quay.io/coreos/etcd:v3.4.9
    networks:
      - etcd
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
      - etcd_03:/etcd_03.etcd
  manager_01:
    build:
      context: .
      dockerfile: cmd/manager/Dockerfile
    command: >
      manager
      --config-dir="/config"
      --etcd-endpoints="http://etcd_01:2379,http://etcd_02:2379,http://etcd_03:2379"
      --verbose
    depends_on:
      - etcd_01
      - etcd_02
      - etcd_03
    networks:
      - etcd
      - symphony
    ports:
      - 15760:15760
    volumes:
      - manager_01:/config
  manager_02:
    build:
      context: .
      dockerfile: cmd/manager/Dockerfile
    command: >
      manager
      --config-dir="/config"
      --etcd-endpoints="http://etcd_01:2379,http://etcd_02:2379,http://etcd_03:2379"
      --verbose
    depends_on:
      - etcd_01
      - etcd_02
      - etcd_03
    networks:
      - etcd
      - symphony
    ports:
      - 15761:15760
    volumes:
      - manager_02:/config
  manager_03:
    build:
      context: .
      dockerfile: cmd/manager/Dockerfile
    command: >
      manager
      --config-dir="/config"
      --etcd-endpoints="http://etcd_01:2379,http://etcd_02:2379,http://etcd_03:2379"
      --verbose
    depends_on:
      - etcd_01
      - etcd_02
      - etcd_03
    networks:
      - etcd
      - symphony
    ports:
      - 15762:15760
    volumes:
      - manager_03:/config
version: "3.7"
volumes:
  etcd_01:
  etcd_02:
  etcd_03:
  manager_01:
  manager_02:
  manager_03:
