networks:
  services:
services:
  block:
    build:
      context: .
      dockerfile: cmd/block/Dockerfile
    command: >
      block
      --bind-interface="eth0"
      --config-dir="/config"
      --manager-addr="manager:15760"
      --verbose
    depends_on:
      - manager
    networks:
      - services
    volumes:
      - block:/config
  consul:
    command: agent -bind '{{ GetInterfaceIP "eth0" }}' -client '{{ GetInterfaceIP "eth0" }}' -dev
    image: consul:1.9
    networks:
      - services
    ports:
      - 8500:8500
    volumes:
      - consul:/consul/data
  manager:
    build:
      context: .
      dockerfile: cmd/manager/Dockerfile
    command: >
      manager
      --bind-interface="eth0"
      --config-dir="/config"
      --consul-addr="http://consul:8500"
      --verbose
    depends_on:
      - consul
    networks:
      - services
    volumes:
      - manager:/config
version: "3.7"
volumes:
  block:
  consul:
  manager:
