networks:
  internal: {}
services: 
  minio:
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    networks:
      - internal
version: '3.6'
