networks:
  apiserver:
  consul:
services:
  apiserver:
    build:
      context: .
      dockerfile: cmd/apiserver/Dockerfile
    command: >
      apiserver
      --bind-interface="eth0"
      --config-dir="/config"
      --consul-addr="http://consul:8500"
      --verbose
    depends_on:
      - consul
    networks:
      - apiserver
      - consul
    volumes:
      - apiserver:/config
  consul:
    command: agent -bind '{{ GetInterfaceIP "eth0" }}' -client '{{ GetInterfaceIP "eth0" }}' -dev
    image: consul:1.9
    networks:
      - consul
    ports:
      - 8500:8500
    volumes:
      - consul:/consul/data
version: "3.7"
volumes:
  apiserver:
  consul:
