networks:
  internal: {}
secrets:
  minio.access_key.txt:
    file: ./docker/secret.d/localhost/minio.access_key.txt
  minio.secret_key.txt:
    file: ./docker/secret.d/localhost/minio.secret_key.txt
  postgres.password.txt:
    file: ./docker/secret.d/localhost/postgres.password.txt
services:
  flyway:
    command: migrate
    depends_on:
      - postgres
    image: boxfuse/flyway:5.2-alpine
    networks:
      - internal
    restart: on-failure
    volumes:
      - ./docker/secret.d/localhost/flyway.conf:/flyway/conf/flyway.conf:rw
      - ./migration:/flyway/sql:rw
  minio:
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    networks:
      - internal
    ports:
      - 15511:9000/tcp
    secrets:
      - source: minio.access_key.txt
        target: access_key
      - source: minio.secret_key.txt
        target: secret_key
    volumes:
      - minio:/data
  postgres:
    networks:
      - internal
    ports:
      - 40178:5432/tcp
    secrets:
      - source: postgres.password.txt
    volumes:
      - postgres:/var/lib/postgresql/data:rw
version: '3.6'
volumes:
  minio: {}
  postgres: {}
